language: ruby
rvm:
- 1.9.3
gemfile:
- Gemfile
env:
  global:
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=qubell-starter-kit-artifacts
  - QUBELL_TENANT=https://express.qubell.com
  - PROVIDER_TYPE=aws-ec2
  - PROVIDER_REGION=us-east-1
  - secure: WxKgJfvOle9DJUh1a3pu0fFbSeL9J+G3fcWvVIwc5yiwta4LgtVotmFmQpQVw3qg8UYLANm7N/jwuxUFXD3uf5d2TQJZzYUFsVJavsXiVA571Ea/WMyCE1Rp8k05aZ8ovqULBrYiLkcCVmh1/yO/90H3xVEtzoBjAZHOPZwuMYU=
  - secure: aJ1FpMdr2VknML9qC3nwtZrqyur35uZ4DlPM1/1dLX3PhxCoKCnINxx/epQeAUnozcv/ZvTipAgEUipJhZjN5kXkGKg40FkffDzYTzLyluCmTxf+t+BJ/eR0v1m1y9rOVFQSkQn5DkmuPxurkQeYlAHGxP+oFDyw99EX76oXqcs=
  - secure: Ey69/ySFn3lL/CQ3WgTW6s5dkfdspulFpGgL3xvaM7IINpkKUiJGUv6ixTdMvomuiI/OQ6FOne4te1R9JoJTBlfoKxYqU9A/YLME6z6TobVmug0Vf2VWLrJJqsMQihBwHwRI7GqWyA5n+vMO8NCN5676Ui2Qh+81vx54GWj0W9w=
  - secure: t5UXnBIBnrPOR5wvjbrYUZZdMY3o5NzincnEGlFwKvVQuBPpMQIi/eqADI2cyDZWlGOCrGdsOq3EAkw8jRoanxB2v7gY+vw/+XnwSM6I5EqISSO3+1U9iGk1WIESUJOFFrFiLroLlFPuoSTJJR9/dt95VQA5Sh0S4FdHq+yMyNk=
  - secure: NzGBpXTAWcnlJwK3w/6XjIFXD3usjHafskl5JOE+2/0MZ0ECAsEawzYrmUPlbwZ1y6EoMiR505yy2niKO660Z5tIg90Y7wvhUI639nuibub4I9ENFGeUZ2W/MZcC5V4ZHxft7GdPhRFIVp8uTnX7nTL2ISRE1XCPNkTeMV4gtS0=
  - secure: B/SgQELCXMt2GOryKV6NZrzQMVVnOBhyNIkBVfIiGDFt6Hl83xLCvn7fAPDjUKjGWUYPJpp7vjOTQnDzQuGaIGAMu2JWYMoezeBQjHbdhleR7Jv0sRne6XKn826wuFt7boTmDYJDTJ+eFLurrscX5xqatPLw923gXn3WNGODIA0=
  - secure: F6TNu7WwlNM1VCSUxcvEfNjWEl3i/Tmst1HZoMmgEJgLNI4S003PFXyPPtO+1btMIDay0KDrOHaX/XtqMGgGQeAGkIExdA2e4TEF6QgXFT9t6WuNzD8xZ6xlN6f2pDE8/LHaiEbd8IjGzrSW82Mk4CNiSZbbkeiq311G92xm7fs=
install:
- sudo apt-get -y -q install python-pip
- sudo pip install -r test/requirements.txt
before_script:
- gem install --version 2.0.15 berkshelf --no-ri --no-rdoc
- gem install --version 0.8.9 faraday --no-ri --no-rdoc
- gem install travis-artifacts --no-ri --no-rdoc
- git submodule update --init --recursive
script: ./build.sh
